name: Solutions

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build
        shell: nix develop .#solutions -c bash {0}
        run: task build

  verify:
    name: Verify
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Verify generated code is up-to-date
        shell: nix develop .#solutions -c bash {0}
        run: task verify
